### ISSUE TITLE
sugestão de mudança no cálculo aleatório

### ISSUE THREAD

**Issue by dvnube** [rafaelvascc/google-meet-dice-roller#1]
opa, boa noite!
cara, muito legal a extensão, parabéns!
dei uma passeada no código e queria sugerir vc alterar a forma como realiza o cálculo aleatório e utilizar a função que está na própria documentação do Math.random():
```
function getRandomIntInclusive(min, max) {
  min = Math.ceil(min);
  max = Math.floor(max);
  return Math.floor(Math.random() * (max - min + 1)) + min;
}
```
o link pra documentação é: https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Math/random

estou sugerindo isso pois, analisando a sua forma de cálculo, reparei que, caso a função Math.random() retorne 1, seu cálculo "aleatório" sempre irá retornar 1 também, independente de todo o resto...
a não ser que o dado tenha mais que 999999999999, aí retorna 10.. se tiver mais que 9999999999999 retornará 100, e assim por diante...

enfim.. zero crítica meu camarada! só uma sugestão pra trazer mais aleatoriedade mesmo \o/

novamente, parabéns! ficou muito maneira e eu e meus amigos estamos utilizando direto

abs!

**Comment by rafaelvascc** [comment]
Eu dei uma olhada no link. Realmente eu devia ter usado esse função já pronta no site da Mozilla.
Mas pode ficar tranquilo com a função que existe, ela simplificada tem quase a mesma lógica, só tem os operadores invertidos.
Substituindo as variáveis:

```
const step = 1 / sides;
const rad = Math.random();
const sub = 1 - rad;
if (sub === 0) {
  sub = 0.000000000001;
}
return Math.ceil(sub / step);

return Math.ceil((1 - rad) / (1/ sides));

return Math.ceil((1 - rad) * sides);

return Math.ceil(sides - sides * rad);`
```

Então o resultado do valor mínimo e máximo  usando o d6 como referencia: 
`Math.ceil(6 - 6 * 0.0000000000000001) == 6`

`Math.ceil(6 - 6 * 0.9999999999999999) == 1`

O que eu devia ter feito era simplificar logo a função, o código ficou feio, mas funciona.
Vou trocar por essa função do MDN porquê enfim... porque não?

A parada mais urgente que tenho pra resolver agora é achar um jeito de não precisar usar essa "tabs" api do google. Muita gente desinstalou a extensão assustada com aquela mensagem que ela tava pedindo permissão pra acessar o histórico de navegação.

**Comment by rafaelvascc** [comment]
Implemented on version1.1.0.
