### ISSUE TITLE
dice roller bug

### ISSUE THREAD

**Issue by pstephanie** [rafaelvascc/google-meet-dice-roller#11]
hi! i've been trying to use the roller but it keep crashing. 
![Screenshot_1](https://user-images.githubusercontent.com/102699685/160934525-e6a5da80-09f7-4225-872f-d585aca16b98.png)

**Comment by rafaelvascc** [comment]
I will take a look during the weekend.

**Comment by rafaelvascc** [comment]
Published a fix. The update should be available in chrome store in a day or so.
