### ISSUE TITLE
Die roller no longer working in Google Meet

### ISSUE THREAD

**Issue by goltz20707** [rafaelvascc/google-meet-dice-roller#12]
The die roller buttons can be used in Google Meet, but it puts the die rolls into the JavaScript console and not the chat window.  The die roller commands ("/roll 3d6" or "/roll Set.Command") are just pasted verbatim into the chat window.

Let me know what diagnostic info you need.

**Comment by rafaelvascc** [comment]
I will take a look during the weekend.

**Comment by rafaelvascc** [comment]
Published a fix. The update should be available in chrome store in a day or so.

**Comment by goltz20707** [comment]
Thanks!

--
Jim Goltz ***@***.******@***.***)
