### ISSUE TITLE
donate

### ISSUE THREAD

**Issue by dvnube** [rafaelvascc/google-meet-dice-roller#2]
ah, outra parada!
fomos tentar fazer a doação mas deve ter alguma configuração do paypal barrando
sugiro vc colocar o link pra donate em BRL também
segue print:
![image](https://user-images.githubusercontent.com/77086998/120583315-57fc5500-c404-11eb-8143-4ace96a4b631.png)

**Comment by rafaelvascc** [comment]
Vou botar um link pro pix depois. Tive que deixar em dólar porque 80% do usuários são dos Estados Unidos.

**Comment by rafaelvascc** [comment]
Implemented on version1.1.0.
