### ISSUE TITLE
Add a scrollbar feature 

### ISSUE THREAD

**Issue by maggiedeuitch** [rafaelvascc/google-meet-dice-roller#5]
Hello, 

When using the dice roll sets, if the set has a lot of commands, you are unable to scroll down the list. Instead, you have to try and tab through the icons in order to see the commands at the bottom and shift+tab back up the list. 
It would helpful if there was a scrollbar to navigate through large dice sets.

**Comment by rafaelvascc** [comment]
Fixed in version 1.1.1. Version will be live in some days, we need to wait Google to approve it.

**Comment by rafaelvascc** [comment]
@maggiedeuitch looks like the version was already approved. Did you get it?

**Comment by maggiedeuitch** [comment]
@rafaelvascc Just checked. Yep, it's working great now. Thank you for the quick fix!
