### ISSUE TITLE
Command syntax issue

### ISSUE THREAD

**Issue by Corinos** [rafaelvascc/google-meet-dice-roller#8]
I'm having trouble seeing where my syntax is off: 
`{
	"Cthulhu": {
		"commands": {
			"Strength":"1d100n{STR}"
		},
		"variables": {
			"STR": ""
		}
	}
}`

**Comment by rafaelvascc** [comment]
Variables do not apply to the `n` option, only to constants and dice count. 
What is the system that needs somethign like this?

**Comment by Corinos** [comment]
This was my attempt to apply the Call of Cthulhu system to the roller.  It's a percentile system where you need to roll under to be successful, so I thought I could use the stats and skills values as variables and use the format above. Obviously I forgot to fill the value for the variable above, but that's what I was trying to do.

**Comment by rafaelvascc** [comment]
@Corinos Ok, i will add it to the todo list for the next version. I will probably do it tomorrow, but google takes its time to approve an update at the Chrome store.

**Comment by rafaelvascc** [comment]
Done on version 1.2.0. Waiting for Google to approve the version in the Chrome store.

**Comment by rafaelvascc** [comment]
@Corinos looks like version 1.2.0 was already published. Did you receive it?
